### ISSUE TITLE
Constructive Criticism for the Parliament Designer

### ISSUE THREAD

**Issue by DrRandomFactor** [slashme/parliamentdiagram#10]
Now let me start off by saying the Parliament Designing tool is flipping fun to play around with. That being said it is not perfect, as nothing is. So I do have a few complaints and suggestions that can be done.

1. Make the layout nicer.

Now I know little about web design and I know CSS is a complete pain in the rear-end to deal with. I know that. But the sites does look a little plain and it would not hurt to have a nicer looking layout, nothing fancy to make the site more professional looking and more streamlined.

2. Make Party boxes more streamlined

I had a bit of an issue with the different boxes for filling out the party since it is all jumbled together and a bit confusing without the numbers on the sides for the specific party. So I propose putting boxes around each party segment as you open it up. Here is a link to a photo on Imgur.com showing what I am talking about. http://imgur.com/hmD68AM

3. Add Westminister style layouts, but 2 different types.

Although many governments have Westminister style party layouts, they don't all follow the British style.

I've noticed they either follow the British style layout, like what Canada does; https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/41st_Can_House.svg/500px-41st_Can_House.svg.png

...or they follow a 'u' shaped pattern, like that the New Zealand Parliament does https://upload.wikimedia.org/wikipedia/commons/2/21/NZ_Parliament_seats%2C_2011.svg

4. Add a box devoted to the Speaker

Many legislatures have speakers and it would be nice to be able to include one. Refer to the New Zealand Parliament to see the Speaker and to get a sense of what it looks like.

5. Make the Westminister-style layout even and make it streamlined.

I've noticed in several legislatures, if they are dominated by a certain party, the opposition partlies look uneven and makes the legislature look like it is lopsided. The New South Wales legislature is a good example of this; https://upload.wikimedia.org/wikipedia/commons/0/07/New_South_Wales_Legislative_Assembly_2014.png

Thank you for taking time to read my concerns! Now let me be a typical Canadian and apologize for being harsh with the criticisms and for wasting your time with this! :) I love life sometimes!

**Comment by slashme** [comment]
I'll open a new bug for the column layout, because I've just fixed it ;-]

**Comment by slashme** [comment]
I've fixed some of these, but others are still open.  Please re-open any open points as new feature requests or bug reports.
