### ISSUE TITLE
The Diagrams looks too wide and skinny

### ISSUE THREAD

**Issue by Gundi444** [slashme/parliamentdiagram#101]
Previously the Arch-style diagrams were thicker. For example: when making the Icelandic Parliament consisting of 63 seats, there used to be 5 seats on each end of the arch. Now there are only 3 seats on each end and that just looks kind of silly. This must have been changed really recently because it used to be the old way two weeks ago when I used the website. Then, everything was fine but now it looks so strange. The way it used to be looked much better than it does now. I hope you understand what I mean and are able to change it back.

**Comment by slashme** [comment]
OK, yes, this is due to a change that @Rade-Mathis and I made recently to avoid the seats in the diagram from being spaced out too widely. I'll change it back now and in a week or two I'll make it an option in the user interface.
