### ISSUE TITLE
Better top-level index/home page

### ISSUE THREAD

**Issue by waldyrious** [slashme/parliamentdiagram#104]
I am able to visit the [/parlitest.php](https://parliamentdiagram.toolforge.org/parlitest.php) URL and see the tool's information, but if I go directly to https://parliamentdiagram.toolforge.org, I get a very plain page asking me for OAuth permission; what's more, once I grant it, visiting that page remains a mostly blank page, with a single unstyled sentence saying:

> You have authorized the parliament diagram tool to post on behalf of Waldyrious. You can now close this window and click the upload link again.

It would be nice if that page provided a better experience for those who reach it other than by clicking an upload link. Pehaps just adding a footnote saying something like

> Didn't reach this page via an uphold link? [Click here](https://parliamentdiagram.toolforge.org/parlitest.php) to go to the home page of the tool.

would already be very helpful.

**Comment by slashme** [comment]
You're right! I will fix this.
