### ISSUE TITLE
Problemas para crear un parlamento 

### ISSUE THREAD

**Issue by huugo04** [slashme/parliamentdiagram#108]
Hola buenas, llevo usando la página sin problemas durante una temporada y a mis amigos les funciona perfectamente, ahora y no se por que los parlamentos no se generan. Lo he intentado hacer en incógnito funciona bien, pero no está permitido hacer capturas y necesito poder hacerlas. No sé qué pasará y espero recibir ayuda. Gracias

**Comment by slashme** [comment]
Hola Hugo,

Para mi, la página funciona sin problemas, y asi que no se cual es el origen del error. ¿Puede añadir alguna información? Porque funciona en el modo incognito, yo creo que el problem no este en el pagina, sino en tu navigador.

**Comment by slashme** [comment]
No further clarification. Closing due to failure to reproduce error
