### ISSUE TITLE
Another bug happened

### ISSUE THREAD

**Issue by InternauteLambda** [slashme/parliamentdiagram#109]
Hi,
Another bug had happened. I've just tried to create a diagram, but it fails, as if I had more than 31k seats. Oddly enough, I was able to create some diagrams many hours ago.

**Comment by slashme** [comment]
Can you please send me the party list? It might be some character or punctuation in one of the party names, for example.

**Comment by InternauteLambda** [comment]
I was using the parties of Spain (UP-PSOE-Cs-PP-Vox), and then, after I noticed the fail, I tried without changing the names (Party 1, Party 2...), with 2 parties, and the fail still happened.

**Comment by slashme** [comment]
I see, something is broken. I'll investigate immediately!

**Comment by slashme** [comment]
Hmm, something's wrong with the CGI: 

`tools.parliamentdiagram@tools-sgebastion-07:~$ tail -3 error.log`
`2021-07-26 22:00:15: (mod_cgi.c.748) stat for cgi-handler /usr/bin/python failed: No such file or directory  `
`2021-07-26 22:00:24: (mod_cgi.c.748) stat for cgi-handler /usr/bin/python failed: No such file or directory  `
`2021-07-26 22:00:40: (mod_cgi.c.748) stat for cgi-handler /usr/bin/python failed: No such file or directory  `

**Comment by slashme** [comment]
Just to keep you informed, I'm on IRC with the site reliability engineer, who's trying to figure out what went wrong.

**Comment by InternauteLambda** [comment]
Thank you for the updates. 👍

**Comment by crookedstorm** [comment]
@slashme I've got you up and running on Toolforge using the testing version of the php7.3 image. I'll put up a patch for review to fix the problem overall (if you do a `webservice stop`, it will reset to the main one, so don't do that until we've made new images).

**Comment by crookedstorm** [comment]
The patch I have up for review to fix this going forward is https://gerrit.wikimedia.org/r/c/operations/docker-images/toollabs-images/+/708187

**Comment by slashme** [comment]
Thank you!!
