### ISSUE TITLE
Non-ASCII characters in party names break diagrams generation

### ISSUE THREAD

**Issue by anton-tsyganenko** [slashme/parliamentdiagram#110]
If non-ASCII characters are used in party names, no diagram is being generated and the following message is given:

> Oops, your diagram wasn't successfully generated! Maybe you have more than 31061 seats. If not, please raise a bug report.

For example, this one works fine:

![image](https://user-images.githubusercontent.com/4764069/127202210-47e00ded-0dac-4a83-b849-4eeac55b4f9a.png)

But if I change party 2 name from "Red" to "Красные":

![image](https://user-images.githubusercontent.com/4764069/127202130-c2d00553-ee23-4f5b-b7f5-6ea452e87ad5.png)

**Comment by slashme** [comment]
I'm on a business trip this week and next week, but will investigate when I get back.
