### ISSUE TITLE
Parliament Diagrams are not working

### ISSUE THREAD

**Issue by Jelican** [slashme/parliamentdiagram#112]
Hi, Parliament Diagrams are not working. I can't make a diagram and upload it to Wikimedia Commons.

**Comment by slashme** [comment]
I just created a diagram and uploaded it. The tool is working. Please try again, and if it still isn't working, create a new bug report with complete details of what you tried, and what error you got.

**Comment by Jelican** [comment]
Okay it works, thanks. the system does not accept the letter Azerbaijani "ə"
