### ISSUE TITLE
US-style diagram not working

### ISSUE THREAD

**Issue by weather512** [slashme/parliamentdiagram#114]
When I try using the US-style diagram, it doesn't work. Nothing happens when I click "Make my diagram".

**Comment by slashme** [comment]
Sorry for the slow response, it was a bit busy in the day job! I'll get right onto this: I guess the latest updates on the arch diagram broke the interface.

**Comment by slashme** [comment]
It should be fixed now: please clear your cache if it doesn't immediately work.
