### ISSUE TITLE
Get party list

### ISSUE THREAD

**Issue by Flpemodesto** [slashme/parliamentdiagram#117]
Hi! I've tried to get my svg on Wikicommons but I cant. My svg is https://commons.wikimedia.org/wiki/File:SenadoBrasil2021.svg
I just should write "File:SenadoBrasil2021.svg" on "Get list of parties from:" box and click "Get party list" button? 
My you try it? File:SenadoBrasil2021.svg
Thanks

**Comment by slashme** [comment]
Hi Filipe,

That option only works if the diagram on Wikipedia already has a list of parties generated by the parliament diagram tool in the file description.
