### ISSUE TITLE
Create US-specific tool

### ISSUE THREAD

**Issue by slashme** [slashme/parliamentdiagram#12]
Request from Shabidoo:

Simple form. Four fields. First two are mandatory. Please don't include the code to generate infobox information per party as this is already on the page and links each party to the state party article and that information will probably be lost if a user cut and pastes it meaning there will be clean up work.

Democrats (0000FF)
Republicans (FF0000)
Independent (C9C9C9)
Vacant (6B6B6B)

A download button next to the generated diagram
A link to the parliament diagram tool if there is a third party

**Comment by shabidoo** [comment]
This is closed. Does that mean it's ready? :)

**Comment by slashme** [comment]
If you go to the site, there's now a link to the US tool. Please give it a
test drive and let me know if it needs any changes.

Cheers,

David
