### ISSUE TITLE
The Cyrillic bug.

### ISSUE THREAD

**Issue by CaptainFlint149** [slashme/parliamentdiagram#125]
Hello, writing from the land of eternal kvass and hardbass. Since recently (most likely since the last update) when entering anything in languages using the Cyrillic alphabet (including Russian) into the "Party X Name" line, the chart simply generates nothing and gives the standard "stub" about exceeding the limit of seats in parliament. And I distinctly remember that before it was possible to do that with ease and without any errors. Please fix this.

In the pictures below is the proof.
![bug1](https://user-images.githubusercontent.com/107560650/173847630-20f39339-8e63-4cce-a71d-76480239ad41.png)
![bug2](https://user-images.githubusercontent.com/107560650/173847642-c04bb0c3-aca1-4c43-81cd-1c5dec1b0b03.png)

**Comment by slashme** [comment]
Привет @CaptainFlint149,

You're quite right! I have a long weekend now and I intend to fix this bug! It's the same as #110 so I'll close this one and report progress there.

Thanks again!!
