### ISSUE TITLE
Parliament diagram tool

### ISSUE THREAD

**Issue by milonhd** [slashme/parliamentdiagram#126]
There is no change in the width of the seats

**Comment by slashme** [comment]
Can you give a bit more detail about what you expected to see, compared to what you did see? What were you trying to change, and what happened?

**Comment by milonhd** [comment]
> what

I want to change the distance between the seats, like in the Sejm of Poland. Is it possible to do this somehow?

**Comment by Gouvernathor** [comment]
Are you talking about the distance between the rows, or about the distance between the seats within a row ?
According to [this](https://commons.wikimedia.org/wiki/File:9th_Term_Sejm_of_Poland.svg), the Sejm does a separation of rows, *and* it adds irregular distances between seats within a row. The latter is not likely to happen within the newarch code.
