### ISSUE TITLE
US specific tool

### ISSUE THREAD

**Issue by shabidoo** [slashme/parliamentdiagram#13]
Great tool. I like the new aesthetic as well.

First...could you please set the default for the independent and vacant to zero? They are more often 0 than not and it would be cumbersome to have to change that.

Is is possible to add a download button next to the rendered diagram. It would save a bit of time.

Could you put democrats in bold and blue, repubs in bold and red and the other two in bold and grey?

Thanks again for making a US specific tool.

**Comment by shabidoo** [comment]
Oh...and when you render the diagram can you put vacant on the very left and independent on the very right (though maintain the order of the entry boxes?)

**Comment by slashme** [comment]
OK, these all seem quick and easy to fix.  I'll do it ASAP (probably this weekend.)  Thanks for logging the request here!

**Comment by slashme** [comment]
Done! Let me know if all works for you.  If it doesn't your browser might not support the "download" attribute, in which case, well, :-/ …
