### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Guntiiiii** [slashme/parliamentdiagram#133]
I was trying to make a hypothetical parliamentary diagram relating to Finnish parliamentary election yesterday, but then the program says that the diagram wasn't successfully generated, and the seats of said hypothetical parliament was around 220, so I think there's a bug. So I submit a bug report so that you could check on the code to see if there're any errors or not.

**Comment by Gouvernathor** [comment]
There are a number of bugs that are in the process of getting fixed in the coming month (if all goes as planned), so that should be considered a probable member of it.
