### ISSUE TITLE
Mention that the website is open source

### ISSUE THREAD

**Issue by ghost** [slashme/parliamentdiagram#134]
Mentioning the license / open source with the github link in the bottom, so people know it's open source ;)
This would help finding the website for those who need to know how it works.
I am creating a Rust application that needs this. Do you think it would be feasible to turn everything into rust code, or should I just do interop with Python? Couldn't find any libraries other than matplotlib that can do this for me.
Thanks.

**Comment by Gouvernathor** [comment]
The license, GPLV2, is shown on the website.
Now that the parliamentarch module is split from the rest (and used by the web service), it can be used separately, be it by reimplementation or by interop use.
