### ISSUE TITLE
Page doesn't open.

### ISSUE THREAD

**Issue by InternauteLambda** [slashme/parliamentdiagram#136]
Hi,

Since a couple of days, I've tried to open the Parliament Diagram Tool page, but it fails, and this message, of which I've made a screenshot, appears. Oddly enough, I've been using the tool without any problems the day before this starts. Is there a way to make it work again.

Thanks in advance.

<img width="709" alt="Capture d’écran, le 2023-10-16 à 10 26 37" src="https://github.com/slashme/parliamentdiagram/assets/74970680/b9ac40a4-0248-4d58-9bea-cd54084a9e22">

**Comment by slashme** [comment]
Hi there,

I needed to restart the webservice. It's up and running again. Thanks for the report!
