### ISSUE TITLE
CJK characters not supported in partylist extraction

### ISSUE THREAD

**Issue by gia2371b** [slashme/parliamentdiagram#137]
So I was about to make a diagram, but every time I tried to use the "Get List of Parties:" tab, it always says that it is probably an old diagram. no matter how old the diagram itself actually is. It also doesn't disappear once I hit "OK", and it has always been stuck in a loop.

Every diagram I make looked like this since then:

https://parliamentdiagram.toolforge.org/svgfiles/2024-01-15-06-59-28-167948-6168672208345511684.svg
<img width="284" alt="image" src="https://github.com/slashme/parliamentdiagram/assets/156645255/44c63e93-a158-4ca5-920e-d2bf173c1f2c">

This is what I wanted the diagram to look like:
![image](https://github.com/slashme/parliamentdiagram/assets/156645255/e63bc97e-3597-421b-aa5c-72af6dc72738)

(Example image: 11th Legislative Yuan)

I am not sure if this is a bug or not. Either way, I am making sure that if there actually a problem, you can help in figuring out what problem is in the diagram generator.

Many thanks.

**Comment by Gouvernathor** [comment]
Can you try this again, both on the [main website](https://parliamentdiagram.toolforge.org/archinputform.php) and on the [Beta](https://parliamentdiagram-beta.toolforge.org/archinputform) version, and tell if it seems to work on either of them ?

**Comment by gia2371b** [comment]
The main website worked, but the beta one doesn't.

**Comment by Gouvernathor** [comment]
> it always says that it is probably an old diagram. no matter how old the diagram itself actually is.

This is due to the kanji in the file description, and it yields a different bug on Beta. I'll see what I can do about it, it's a regex problem.

> It also doesn't disappear once I hit "OK", and it has always been stuck in a loop.

I didn't see that happening.

> Every diagram I make looked like this since then

What is the problem actually ?

**Comment by Gouvernathor** [comment]
Now it should be fixed on the Beta
