### ISSUE TITLE
Not Generating Parliaments Properly

### ISSUE THREAD

**Issue by jonasthejew** [slashme/parliamentdiagram#140]
I am able to set everything up just fine, but when I click "make my diagram", the diagram doesn't really generate. If I download it, it downloads it in an unusual format that I can't even open. I've tried what I can, but it doesn't seem to work

**Comment by slashme** [comment]
Hi Jonas,

We are aware of this issue, and we're working to try to solve the problem. Hopefully it will be up again soon!

**Comment by TerryJerry47** [comment]
The problem persists, unsure if you think it's been resolved or not, but it continues to not work regardless. Sorry if I'm being a bit rude, just trying to let you know

**Comment by slashme** [comment]
I'll close this issue when it's working again, so as long as it's open, we're still working to fix it.

**Comment by jonasthejew** [comment]
> Hi Jonas,
> 
> We are aware of this issue, and we're working to try to solve the problem. Hopefully it will be up again soon!

Good to know. Thank you for your responsiveness!

**Comment by slashme** [comment]
Solved by @Gouvernathor ! It was a server-side problem: lighttpd needed to be told to run the script with python3.
