### ISSUE TITLE
Upload function doesn't work

### ISSUE THREAD

**Issue by InternauteLambda** [slashme/parliamentdiagram#148]
Hi,
There's a problem with uploading. When you press the button to upload, the page that open is a full white page, with "400 Bad Request" written in the left corner.

Is there a way to make it upload again?

Thank you in advance.

**Comment by Gouvernathor** [comment]
That should be fixed in the [Beta version](https://parliamentdiagram-beta.toolforge.org/) of the tool. Let me know on #161 if that works.
