### ISSUE TITLE
Error (code "abusefilter-disallowed")

### ISSUE THREAD

**Issue by Loyalluz** [slashme/parliamentdiagram#168]
When i try to update new parliament tool this is show me Error (code "abusefilter-disallowed"):
⧼abusefilter-warning-file-overwriting⧽
Please raise an issue on the GitHub Issue tracker if the error seems internal to the Tool.

**Comment by Gouvernathor** [comment]
This is due to the permissions that Wikimedia Commons gives to users : you don't have the powers necessary to overwrite a file.
That's Wikimedia policy. If you use a non-existing file name, it should work fine.
