### ISSUE TITLE
Tool fails to upload to WP

### ISSUE THREAD

**Issue by InternauteLambda** [slashme/parliamentdiagram#180]
Hi,
The tool fails to upload the diagrams to Wikipedia Commons. I've tried a couple of times, and all of them failed.
When I press upload, I get this message:
"Error (code "abusefilter-disallowed"):
⧼abusefilter-warning-file-overwriting⧽"

On top of that, it is asked to report the problem here, on GH. So, here it is.

Thanks in advance for solving the problem.

**Comment by InternauteLambda** [comment]
So, 6 weeks later, it hasn't changed. Am I the only one with that problem?
I still have this message when trying to upload:
"Error (code "abusefilter-disallowed"):
⧼abusefilter-warning-file-overwriting⧽"

**Comment by Gouvernathor** [comment]
That's an issue with Wikimedia's policy on file uploads : users aren't allowed to overwrite files not their own - or to overwrite files, period. Creating new files with new names should work, though that too should not be abused.
There may be a better way for this website to react to and display the error message.

**Comment by InternauteLambda** [comment]
Ah ok. That's weird because I would rarely overwrite files. I'd do a file of an existing diagram with a different name (eg.: in French vs. english), and it wouldn't work anyway. I even did original work and it didn't upload.
I just tried it after I receive a notification, and I was able to upload. I'm glad it's back!
Thank you.
