### ISSUE TITLE
XML Parsing Error on special characters

### ISSUE THREAD

**Issue by aayushsrathore** [slashme/parliamentdiagram#181]
**Description:** Political parties with special characters in their name, most notably "&" would result in an XML parsing error and lead to the svg showing error messages.
Different errors are shown if the location of the special symbol is different.

**To replicate the issue**, try using the symbols '&' or accent marks and hyphens which are common usage in politicial parties in Spanish or French-speaking areas.
Here is the issue if the first political party's name contains a special character
![image](https://github.com/user-attachments/assets/cdb105bd-f385-4591-949c-6de8f321c1e1)
OS: Windows 10

**Comment by Gouvernathor** [comment]
So it's the resulting SVG image that fails to load, not the tool itself ?

**Comment by aayushsrathore** [comment]
The error is different depending on the position of the special character so it could be parsing error, still the tool works fine, it's the SVG that fails to load.

**Comment by Gouvernathor** [comment]
Fixed in 38826b19ccc45238a90cd8a8d49ff68383ab30db
