### ISSUE TITLE
셰이마스

### ISSUE THREAD

**Issue by z234222** [slashme/parliamentdiagram#184]
제국연방의회 집권여당
농민녹색연합 의석
입니다
![Uploading 2024-12-18-03-44-39-925299-d792fb86cae8dbac3ef15087cb8a2e1d7717a8039a462402cebe7f26a1fdfffb.svg…]()

**Comment by Gouvernathor** [comment]
![image](https://github.com/user-attachments/assets/c76efd92-d04c-459c-a961-d6bedf9394f4)

Seems to work on my end.
