### ISSUE TITLE
Single-row semi-circles and circles

### ISSUE THREAD

**Issue by JackWilfred** [slashme/parliamentdiagram#35]
I would like to be able to create semi-circles of only a single row of seats. I imagine this will be useful for the London Assembly (which sits in both circle and semi-circle, but only ever one row) and the Gibraltar Parliament (which sits in a single-row circle).

**Comment by slashme** [comment]
The aim of this tool is not to generate accurate representations of the different seating arrangements of various legislatures, but to generate generic, readable diagrams.

**Comment by slashme** [comment]
The request for flexible diagram shapes is such a perennial request that I'm reopening it at https://github.com/slashme/parliamentdiagram/issues/42
