### ISSUE TITLE
Colours are coordinated on mobile

### ISSUE THREAD

**Issue by emass100** [slashme/parliamentdiagram#38]
When I tried it, both parties had the same colour. The only way I can make parties copies look different is if I adjust the darkness, but I can't get any red vs blue colors schemes going. I am using an iPhone.

**Comment by slashme** [comment]
What happens when you type a color into the color box, for example ff0000
for red or 0000ff for blue?

**Comment by emass100** [comment]
I tried typing it and it worked well! Thank you! I'm having issues when I am selecting the colour though.

**Comment by emass100** [comment]
Here's a GIF of what I am experiencing.
![giphy](https://cloud.githubusercontent.com/assets/20388485/16721526/1dddbe74-46fd-11e6-83fe-bd82d4509fd3.gif)

**Comment by slashme** [comment]
I just checked, and this doesn't affect the default Android browser.

**Comment by emass100** [comment]
It affected me on my iPhone.

2017-03-01 5:02 GMT-05:00 David Richfield <notifications@github.com>:

**Comment by slashme** [comment]
I get that, and I'm certainly not closing this bug - I'll just have to get around to fixing it when I have time and access to an iPhone. Thanks again for the very clear and helpful report!

**Comment by slashme** [comment]
Is this still an issue on the iPhone?

**Comment by emass100** [comment]
No, it’s all fixed now!

Le mar. 1 déc. 2020 à 13:41, David Richfield <notifications@github.com> a
écrit :

**Comment by slashme** [comment]
Thank you!
