### ISSUE TITLE
Small Parliaments

### ISSUE THREAD

**Issue by lawrencedepe** [slashme/parliamentdiagram#39]
I use this for a political game, and I need a 9-member arch-style diagram. Unfortunately, it automatically sets it out in two circular rows, with 6 at the back and 3 at the front. This looks awfully dodgy and way too spaced out, so I would just like to request that you consider making these smaller diagrams (maybe 10 seats and under) all in one row. Thanks!

**Comment by slashme** [comment]
I completely agree. I'll make this change soon.

**Comment by lawrencedepe** [comment]
I just had a look, if it helps, but it is only up to 9 and down to 4. 3 seats is in one row and 10 seats looks fine.

**Comment by bcharles** [comment]
Displaying small parliaments with a smaller arch size would help make the spacing of seats more even.  The spacing between rows is much smaller than the spacing within a row.  Try a 17 seat parliament, for example. - e.g. https://commons.wikimedia.org/wiki/File:Philadelphia_City_Council_makeup.svg

**Comment by slashme** [comment]
This issue has been mostly fixed by @Rade-Mathis
