### ISSUE TITLE
Ability to set border colour for parties?

### ISSUE THREAD

**Issue by sarahlicity** [slashme/parliamentdiagram#46]
In the British legislature diagrams, white is typically used for vacant seats, as opposed to grey, which is typically used for Independents.

Of course, white doesn't show up well in infoboxes–[see the article for the National Assembly of Wales](https://en.wikipedia.org/wiki/National_Assembly_for_Wales)–so the ability to set a border from the tool would be much appreciated.

**Comment by slashme** [comment]
Hi Sarah,

I've finally gotten around to making a prototype - sorry for the long wait!!

Please check out https://tools.wmflabs.org/parliamentdiagram/parlitest2.php and let me know whether this would work.

**Comment by sarahlicity** [comment]
Yep, that works perfectly.

**Comment by slashme** [comment]
Thanks for the feedback! It's now implemented at https://tools.wmflabs.org/parliamentdiagram/parlitest.php - I'll probably make that the standard interface soon, so I'm not going to bother to make the change at https://tools.wmflabs.org/parliamentdiagram/parliamentinputform.html as well.
