### ISSUE TITLE
Have the ability for a party to have 0 seats.

### ISSUE THREAD

**Issue by N-Si** [slashme/parliamentdiagram#51]
Currently when you set a party to have 0 seats, it still puts in 1 when you make the diagram. 
Being able to add 0 seats would be convenient when making a series of diagrams, because then you would not have to delete a party every time it doesn't have any seats and then have to re-add it back and fiddle around with placing when it gains seats again.

**Comment by slashme** [comment]
Not sure when this got fixed, but it's fixed :-)
