### ISSUE TITLE
Missing links and long loading times

### ISSUE THREAD

**Issue by MilesW-98** [slashme/parliamentdiagram#54]
For some reason when I tried to get onto the page it took way longer for the site to load, not only that, parts of the site were missing at the top and bottom, and the diagram wouldn't work, not allowing me to create a party or even make my diagram

![Screenshot_7](https://user-images.githubusercontent.com/48692365/54553806-6bd55100-4989-11e9-8a08-dcc3f6b95d8a.png)

**Comment by slashme** [comment]
Can you please check whether it's still having problems? I've migrated it to the new Debian Stretch server now, and everything's working fine from here in Germany.
