### ISSUE TITLE
color choice issue westminster diagram

### ISSUE THREAD

**Issue by ArminRbn** [slashme/parliamentdiagram#65]
Hi, 

I can't choose the color anymore, i can only copy past the color value and it is annoying
Thanks in advance
![Annotation 2019-09-22 141059](https://user-images.githubusercontent.com/55656529/65387012-e0c38200-dd42-11e9-8e03-44fd570779a0.png)

**Comment by slashme** [comment]
Fixed!

**Comment by ArminRbn** [comment]
now it works :) thanks!
