### ISSUE TITLE
The site is still down

### ISSUE THREAD

**Issue by ArminRbn** [slashme/parliamentdiagram#71]
the website still does not work ; I don't know why
![Annotation 2020-01-22 101930](https://user-images.githubusercontent.com/55656529/72881261-b984bd80-3d00-11ea-8ad6-467a40bb2a76.png)

**Comment by slashme** [comment]
It's down again, not still! I'm at work now, so I can't restart the webservice for the next 8 hours or so, sorry.  I'll ask the administrators to find out why it keeps crashing.

**Comment by slashme** [comment]
The site is up again. I'll try to diagnose the problem based on the project's error logs. Tracking this in [issue 72](https://github.com/slashme/parliamentdiagram/issues/72)
