### ISSUE TITLE
Move political parties around

### ISSUE THREAD

**Issue by smashter** [slashme/parliamentdiagram#76]
It would be more convenient if instead of copying and pasting policial parties, the number of seats they obtained, and their color into new/different slots in the arch diagram maker that a toggle to move the party ranks up and down on preference could be implemented instead.

**Comment by slashme** [comment]
Good suggestion, related to #50

**Comment by Gouvernathor** [comment]
It would even make it obsolete in my view.

**Comment by Gouvernathor** [comment]
Done on Arch, needs to be done for Westminster as well (and the upcoming Templates too).
