### ISSUE TITLE
Diagram generation fails when party name has a comma

### ISSUE THREAD

**Issue by ajanvier** [slashme/parliamentdiagram#77]
Hello,

I'm trying to generate diagrams with parties (actually lists of candidates) that contains commas, like `Avec Olivier Capitanio, Maisons-Alfort d'abord` but everytime it fails with the following error : 
> Oops, your diagram wasn't successfully generated! Maybe you have more than 31061 seats. If not, please raise a bug report.

I will try to take a look at that and suggest a pull request whenever I get some free time, but meanwhile if anybody else wants to fix that issue it would be greatly appreciated.

**Comment by slashme** [comment]
OK, thanks for the offer! It should be pretty straightforward: I construct a string in the website and then split it in the python script, but I clearly didn't think of protecting commas. 

I will also take a look over the weekend, but it's always cooler to have more contributors on a project, so I would be really happy if you beat me to it!

**Comment by slashme** [comment]
Fixed by @Rade-Mathis - thank you!

**Comment by slashme** [comment]
Oops, that didn't fix it! Reopening.

**Comment by slashme** [comment]
@ajanvier sorry that I was so lazy! Finally your bug got fixed, partly thanks to @Rade-Mathis

**Comment by ajanvier** [comment]
Well thanks to you both @Rade-Mathis @slashme !
I forgot about that issue but it's nice to see it fixed 😄
