### ISSUE TITLE
Still got issues

### ISSUE THREAD

**Issue by InternauteLambda** [slashme/parliamentdiagram#85]
Hi, I was trying to create another diagram and it didn't work. I have enter all the details (names, seats, colors), and when I clicked "Make my diagram", it said "Oops, your diagram wasn't successfully generated! Maybe you have more than 31061 seats. If not, please raise a bug report." in red. The diagrams I was doing weren't near 31k seats.
Also, it seems it's not the first time it happened. That problem happened a month ago or so.
Thanks in advance for solving it.

**Comment by slashme** [comment]
Hey there, can you give me the list of parties that you used? That will help me to find the bug.

**Comment by InternauteLambda** [comment]
I did not use any list from a specific country. I added them all by hand. The one I was working on was a town council with 13 different parties. And I made some like that before (some times with more parties than that) without any problem.

**Comment by slashme** [comment]
If you try to make the diagram with the exact same parties and the exact same number of seats per party, does it always fail? If so, I need to know the exact names of the parties so that I can see what's causing the trouble. For example, something that I need to fix (and will be fixing in the next few days) is that any party name with a comma causes a problem.

**Comment by InternauteLambda** [comment]
Well, I've tried to change different things, and still the same message. I've also created diagrams yesterday without changing the names or the default colors (just adding a number of seats) to see if the problem was solved, and still the same message.
And the names didn't use any comas.
Although, last week, I use the "&" sign and I got a different message reporting the problem than that one in red. I removed it then, and it was solved.

**Comment by slashme** [comment]
OK, I just tested, and it works for me. It might be that your browser is caching the old Javascript. Try doing a shift-reload of the page, so that it reloads everything without relying on the page cache.

**Comment by InternauteLambda** [comment]
It seems that my JavaScript is indeed having problems. I have this message showing in the JavaScript: "Failed to load resource: the server responded with a status of 500 ()"
Problem is I'm not good at programming, so I don't know how to reload without the page cache. I'm using a new Mac.

**Comment by slashme** [comment]
I just checked, and on a mac, you can bypass the cache by holding down the shift button and clicking the reload button on your browser.

**Comment by InternauteLambda** [comment]
Awesome! It worked! Thank you very much!

**Comment by slashme** [comment]
So glad it works now!
