### ISSUE TITLE
Westminister diagram tab is broken?

### ISSUE THREAD

**Issue by fab144** [slashme/parliamentdiagram#86]
Why is the westminister parliment diagram chart broken?

**Comment by slashme** [comment]
Oops, it's a problem with the link to the CSS file. I'll fix it  when I get home in about 5 hours. It's a trivial fix, but I don't have access to the servers from work.

**Comment by slashme** [comment]
There's a workaround: you can press F12 and then in the code, expand the "head" section and change href="parliamentstyle.css" to href="css/parliamentstyle.css"
![Workaround1](https://user-images.githubusercontent.com/414507/100230152-9ed53380-2f25-11eb-91d9-ceea71e5da4a.png)
![Workaround2](https://user-images.githubusercontent.com/414507/100230155-a0066080-2f25-11eb-87cb-9fb3d1dd28e2.png)
![Workaround3](https://user-images.githubusercontent.com/414507/100230159-a09ef700-2f25-11eb-9c51-dedd1e1a24ed.png)

**Comment by slashme** [comment]
Fixed!
