### ISSUE TITLE
Blocked by mistake?

### ISSUE THREAD

**Issue by InternauteLambda** [slashme/parliamentdiagram#91]
Hi,
I tried to upload a diagram, and when it asked for authorization on Wiki Commons, I click the right button (I think, I clicked quickly), but then when trying to upload it for real, it said I got blocked ("Error: Your IP address has been blocked automatically, because it was used by a blocked user."). The blocking is not on Commons though, it seems to be here.
Is it possible to correct that and stop the blocking on my IP address?
Thanks in advance.
InternauteLambda

**Comment by slashme** [comment]
Hmm, I'm having the same problem. I'm not sure what's going on: I guess Toolforge got blocked for some reason. I'll try to find out and let you know.

**Comment by slashme** [comment]
Now it seems to be working again. Let me know if it works for you too.
