### ISSUE TITLE
Installation ins't straightforward because of missing files

### ISSUE THREAD

**Issue by Rade-Mathis** [slashme/parliamentdiagram#92]
I am currently installing your website on my own server for development purpose.

Installing it as cloned from GitHub won't work because files are missing :

* Libs
  * jscolor.js
  * select2.min.js
  * select2.min.css
* Images
  * The 3 thumbnails for the diagram types on the top of the page

Should I push / pullRequest them, in order to have a more straightforward install ? Or are they missing on purpose ?

**Comment by slashme** [comment]
I didn't include the external assets in this repository because I didn't want to worry about license issues, but if you can take a look at the licensing status, is happily accept a pull request!

**Comment by slashme** [comment]
Thank you, fixed!
